# -*- coding: utf-8 -*-
"""Colaboratory에 오신 것을 환영합니다

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from google.colab import files
files.upload()

import pandas as pd
import datetime
import matplotlib.pyplot as plt
data = pd.read_excel('seoul_covid_19.xlsx')

yo = ['월', '화', '수', '목', '금', '토', '일']
region_name = data['지역'].drop_duplicates().sort_values().tolist()
graph = pd.DataFrame()
for i in range(len(region_name)) : 
  a = []
  b = []
  start_date = datetime.datetime(2020,1,20)
  end_date = datetime.datetime(2021,10,10)
  next_date = start_date + datetime.timedelta(days = 6)
  date_range = data[data.지역 == region_name[i]]['확진일'].sort_values().tolist()
  data_index = data[data.지역 == region_name[i]].sort_values('확진일')
  #
  date_time = data_index
  data_index.set_index('확진일',inplace=True)
  while start_date < end_date :
    every = date_time.loc[start_date : next_date]
    a.append(len(every))
    b.append(start_date)
    #graph = graph.append({region_name[0] : len(every)},ignore_index=True)
    start_date = start_date + datetime.timedelta(days = 7)
    next_date = next_date + datetime.timedelta(days = 7)
  graph[region_name[i]] = a

plt.figure(figsize=(20,10))
plt.xlabel('WEEK')
plt.ylabel('Number')
x_values = b
h = ['GangNam', 'GangDong', 'GangBuk', 'GangSeo', 'GwanAk', 'GwangJin', 'Guro', 'GeumCheon', 'ETC', 'NoWon', 'DoBong', 'DDM', 'DongJak', 'Mapo', 'SDM', 'SeoCho', 'SD', 'SB', 'SongPa', 'YangCheon', 'YDP', 'YongSan', 'EP', 'JongNo', 'JungGu', 'JungNang', 'Other City']
for k in range(graph.shape[1]) :
  y_values = graph[graph.columns[k]].tolist()
  plt.plot(x_values, y_values, label = h[k])
plt.legend()
plt.show()

